### ISSUE TITLE
Meter to mile converter 

### ISSUE THREAD

**Issue by abdulazeeznaji** [nosibah93/first-HTML#2]
I tried your app it's so cool, however  when I am passing 1.8 meters it's giving me 1.1 in a mile, maybe your converter needs to accept the value

**Comment by nosibah93** [comment]
> I tried your app it's so cool, however when I am passing 1.8 meters it's giving me 1.1 in a mile, maybe your converter needs to accept the value

i fix it . you can try it again and it will give you right result .
